apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
spec:

  type: NodePort
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 80
    nodeport: 30080
  selector:
    app: sample-app
